version: '3.8'

services:
  web:
    build: .
    container_name: django_task_manager
    restart: always
    command: gunicorn your_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_password
    ports:
      - "5432:5432"
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  celery:
    build: .
    container_name: celery_worker
    restart: always
    command: celery -A your_project worker --loglevel=info
    depends_on:
      - web
      - redis
    networks:
      - app_network

  celery-beat:
    build: .
    container_name: celery_beat
    restart: always
    command: celery -A your_project beat --loglevel=info
    depends_on:
      - web
      - redis
    networks:
      - app_network

  channels:
    build: .
    container_name: django_channels
    restart: always
    command: daphne -b 0.0.0.0 -p 8001 your_project.asgi:application
    ports:
      - "8001:8001"
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
